### ISSUE TITLE
fail during installation

### ISSUE THREAD

**Issue by dawnmy** [hzi-bifo/seq2geno2pheno#7]
After run the `./INSTALL.sh` to create the conda environment, the following error appears:

```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - openblas==0.3.5=h9ac9557_1001
```

**Comment by thkuo** [comment]
The installation script is updated. Please feel free to reopen this issue if it still could not solve. Thanks
