### ISSUE TITLE
how to get the AST result of samples from your article which about resistance predict？

### ISSUE THREAD

**Issue by feihongloveworld** [hzi-bifo/seq2geno2pheno#8]
hi sir：
    It is a good job in <Predicting antimicrobial resistance in Pseudomonas aeruginosa with machine learning-enabled molecular diagnostics>,
   i want to get the AST ，and use your methd to predict many Pseudomonas aeruginosa resistance，
thanks

**Comment by thkuo** [comment]
Thank you for your interest (and waiting for long time). For the prediction, what data do you currently have or plan to start with? That could allow us to assist you more precisely.

**Comment by feihongloveworld** [comment]
> Thank you for your interest (and waiting for long time). For the prediction, what data do you currently have or plan to start with? That could allow us to assist you more precisely.
hi sir:
       WGS and mNGS data, i will get the Accuracy of predictor ,and use it in mNGS data.

**Comment by thkuo** [comment]
Unfortunately this tool currently is designed for single-species data, although adding analyses about metagenome data sure is insightful. 
If you already have precomputed features, however, an alternatively method to metagenome dataset is to manually format your input data for Geno2Pheno (as described https://github.com/hzi-bifo/Geno2PhenoClient/tree/3b17d5aed376aee652493b781389acd3a2c7ff05#config-modification), validate them, and have the compressed data and parameters submitted to the server.

**Comment by feihongloveworld** [comment]
hi sir:
      mNGS is a headachei work on resistance，i will try in WGS data first step, and to evaluate the feasibility in mNGS。
this maybe  impossible，but it's my work for boss.so i need test Existing methods and get more AST sample。
so can you provide some AST sample for me ？
thanks ......（God bless my work）

**Comment by thkuo** [comment]
We recommend you to choose some published data that look similar to what you will be analyzing (species, drugs ..etc). In case you really need a starting point, (a subset of) our previous paper might be helpful. https://www.embopress.org/doi/full/10.15252/emmm.201910264

**Comment by feihongloveworld** [comment]
i have read the literature，and got the ast info，thanks
